services:
  mysql-db:
    image: mysql:8.0
    container_name: database_project
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: club_registration
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: database_project_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: clubsystem
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
