import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans_Thai } from "next/font/google"
import Navbar from "@/components/Navbar"
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

const ibmPlexThai = IBM_Plex_Sans_Thai({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["thai", "latin"],
  variable: "--font-ibm-plex-thai",
});

export const metadata: Metadata = {
  title: "UGMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body className={`${inter.variable} ${ibmPlexThai.variable} font-sans antialiased`}>
          <Navbar/>
            <main className="pt-20">
              {children}
            </main>
      </body>
    </html>
  );
}
